/*
 Copyright (c) 2014, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @link      http://buildwithcraft.com
*/
(function(a){Craft.Installer=Garnish.Base.extend({$bg:null,$screens:null,$currentScreen:null,$accountSubmitBtn:null,$siteSubmitBtn:null,loading:!1,init:function(){this.$bg=a("#bg");this.$screens=Garnish.$bod.children(".modal");this.addListener(a("#beginbtn"),"activate","showAccountScreen")},showAccountScreen:function(b){this.showScreen(1,a.proxy(function(){a("#beginbtn").remove();this.$accountSubmitBtn=a("#accountsubmit");this.addListener(this.$accountSubmitBtn,"activate","validateAccount");this.addListener(a("#accountform"),
"submit","validateAccount")},this))},validateAccount:function(b){b.preventDefault();this.validate("account",["username","email","password"],a.proxy(this,"showSiteScreen"))},showSiteScreen:function(){this.showScreen(2,a.proxy(function(){this.$siteSubmitBtn=a("#sitesubmit");this.addListener(this.$siteSubmitBtn,"activate","validateSite");this.addListener(a("#siteform"),"submit","validateSite")},this))},validateSite:function(b){b.preventDefault();this.validate("site",["siteName","siteUrl"],a.proxy(this,
"showInstallScreen"))},showInstallScreen:function(){this.showScreen(3,a.proxy(function(){for(var b="username email password siteName siteUrl locale".split(" "),d={},c=0;c<b.length;c++){var e=b[c],f=a("#"+e);d[e]=Garnish.getInputPostVal(f)}Craft.postActionRequest("install/install",d,a.proxy(this,"allDone"),{complete:a.noop})},this))},allDone:function(b,d){if("success"==d&&b.success){this.$currentScreen.find("h1:first").text(Craft.t("All done!"));var c=a('<div class="buttons"/>'),e=a('<div class="btn big submit">'+
Craft.t("Go to Craft")+"</div>").appendTo(c);a("#spinner").replaceWith(c);this.addListener(e,"click",function(){this.showScreen(30,null,1E3);setTimeout(function(){window.location.href=Craft.getUrl("dashboard")},Craft.Installer.duration)})}else this.$currentScreen.find("h1:first").text("Oops.")},showScreen:function(b,d,c){c||(c=Craft.Installer.duration);this.$bg.animate({left:"-"+5*b+"%"},c);c=Garnish.$win.width();var e=Math.floor(c/2);this.$currentScreen&&this.$currentScreen.css("left",e).animate({left:-400},
Craft.Installer.duration);this.$currentScreen=a(this.$screens[b-1]).css({display:"block",left:c+400}).animate({left:e},Craft.Installer.duration,a.proxy(function(){this.$currentScreen.css("left","50%");this.focusFirstInput();d()},this))},validate:function(b,d,c){if(!this.loading){this.loading=!0;a("#"+b+"form").find(".errors").remove();var e=this["$"+b+"SubmitBtn"];e.addClass("sel loading");b="install/validate"+Craft.uppercaseFirst(b);for(var f={},g=0;g<d.length;g++){var m=d[g],n=a("#"+m);f[m]=Garnish.getInputPostVal(n)}Craft.postActionRequest(b,
f,a.proxy(function(b,d){this.loading=!1;e.removeClass("sel loading");if("success"==d)if(b.validates)c();else{for(var f in b.errors){for(var g=b.errors[f],h=a("#"+f),k=h.closest(".field"),k=a('<ul class="errors"/>').appendTo(k),l=0;l<g.length;l++)a("<li>"+g[l]+"</li>").appendTo(k);h.is(":focus")||(h.addClass("error"),a.proxy(function(a){this.addListener(a,"focus",function(){a.removeClass("error");this.removeListener(a,"focus")})},this)(h))}Garnish.shake(this.$currentScreen)}},this))}},focusFirstInput:function(){setTimeout(a.proxy(function(){this.$currentScreen.find("input:first").focus()},
this),Craft.Installer.duration)}},{duration:300});Garnish.$win.on("load",function(){Craft.installer=new Craft.Installer})})(jQuery);

//# sourceMappingURL=install.min.map
