/*
 Copyright (c) 2014, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @link      http://buildwithcraft.com
*/
(function(c){Craft.MatrixInput=Garnish.Base.extend({id:null,blockTypes:null,blockTypesByHandle:null,inputNamePrefix:null,inputIdPrefix:null,maxBlocks:null,$container:null,$blockContainer:null,$addBlockBtnContainer:null,$addBlockBtnGroup:null,$addBlockBtnGroupBtns:null,blockSort:null,totalNewBlocks:0,init:function(a,b,d,g){this.id=a;this.blockTypes=b;this.inputNamePrefix=d;this.inputIdPrefix=Craft.formatInputId(this.inputNamePrefix);this.maxBlocks=g;this.$container=c("#"+this.id);this.$blockContainer=
this.$container.children(".blocks");this.$addBlockBtnContainer=this.$container.children(".buttons");this.$addBlockBtnGroup=this.$addBlockBtnContainer.children(".btngroup");this.$addBlockBtnGroupBtns=this.$addBlockBtnGroup.children(".btn");this.$addBlockMenuBtn=this.$addBlockBtnContainer.children(".menubtn");this.setNewBlockBtn();this.blockTypesByHandle={};for(b=0;b<this.blockTypes.length;b++)a=this.blockTypes[b],this.blockTypesByHandle[a.handle]=a;d=this.$blockContainer.children();g=Craft.MatrixInput.getCollapsedBlockIds();
this.blockSort=new Garnish.DragSort(d,{caboose:"<div/>",handle:"> .actions > .move",axis:"y",helperOpacity:0.9});for(b=0;b<d.length;b++){var h=c(d[b]);a=h.data("id");(a="string"==typeof a&&a.match(/new(\d+)/))&&a[1]>this.totalNewBlocks&&(this.totalNewBlocks=parseInt(a[1]));a=new n(this,h);a.id&&-1!=c.inArray(""+a.id,g)&&a.collapse()}this.addListener(this.$addBlockBtnGroupBtns,"click",function(a){a=c(a.target).data("type");this.addBlock(a)});new Garnish.MenuBtn(this.$addBlockMenuBtn,{onOptionSelect:c.proxy(function(a){a=
c(a).data("type");this.addBlock(a)},this)});this.updateAddBlockBtn();this.addListener(this.$container,"resize","setNewBlockBtn")},setNewBlockBtn:function(){30<this.$addBlockBtnGroup.removeClass("hidden").height()?(this.$addBlockBtnGroup.addClass("hidden"),this.$addBlockMenuBtn.removeClass("hidden")):(this.$addBlockBtnGroup.removeClass("hidden"),this.$addBlockMenuBtn.addClass("hidden"))},canAddMoreBlocks:function(){return!this.maxBlocks||this.$blockContainer.children().length<this.maxBlocks},updateAddBlockBtn:function(){this.canAddMoreBlocks()?
(this.$addBlockBtnGroup.removeClass("disabled"),this.$addBlockMenuBtn.removeClass("disabled")):(this.$addBlockBtnGroup.addClass("disabled"),this.$addBlockMenuBtn.addClass("disabled"))},addBlock:function(a,b){if(this.canAddMoreBlocks()){this.totalNewBlocks++;for(var d="new"+this.totalNewBlocks,g='<div class="matrixblock" data-id="'+d+'"><input type="hidden" name="'+this.inputNamePrefix+"["+d+'][type]" value="'+a+'"/><input type="hidden" name="'+this.inputNamePrefix+"["+d+'][enabled]" value="1"/><div class="actions"><div class="status off" title="'+
Craft.t("Disabled")+'"></div><a class="settings icon menubtn" title="'+Craft.t("Actions")+'" role="button"></a> <div class="menu padded" data-align="right"><ul><li><a data-icon="collapse" data-action="collapse">'+Craft.t("Collapse")+'</a></li><li class="hidden"><a data-icon="expand" data-action="expand">'+Craft.t("Expand")+'</a></li><li><a data-icon="disabled" data-action="disable">'+Craft.t("Disable")+'</a></li><li class="hidden"><a data-icon="enabled" data-action="enable">'+Craft.t("Enable")+"</a></li></ul><hr/><ul>",
h=0;h<this.blockTypes.length;h++)var l=this.blockTypes[h],g=g+('<li><a data-icon="+" data-action="add" data-type="'+l.handle+'">'+Craft.t("Add {type} above",{type:l.name})+"</a></li>");var g=g+('</ul><hr/><ul><li><a data-icon="remove" data-action="delete">'+Craft.t("Delete")+'</a></li></ul></div><a class="move icon" title="'+Craft.t("Reorder")+'" role="button"></a> </div></div>'),f=c(g);b?f.insertBefore(b):f.appendTo(this.$blockContainer);var k=c('<div class="fields"/>').appendTo(f),g=this.getParsedBlockHtml(this.blockTypesByHandle[a].bodyHtml,
d),e=this.getParsedBlockHtml(this.blockTypesByHandle[a].footHtml,d);c(g).appendTo(k);f.css(this.getHiddenBlockCss(f)).animate({opacity:1,"margin-bottom":14},"fast",c.proxy(function(){f.css("margin-bottom","");c("body").append(e);Craft.initUiElements(k);new n(this,f);this.blockSort.addItems(f);this.updateAddBlockBtn()},this))}},getHiddenBlockCss:function(a){var b=-a.outerHeight();a.is(":only-child")&&(b-=10);return{opacity:0,marginBottom:b}},getParsedBlockHtml:function(a,b){return"string"==typeof a?
a.replace(/__BLOCK__/g,b):""}},{collapsedBlockStorageKey:"Craft-"+Craft.siteUid+".MatrixInput.collapsedBlocks",getCollapsedBlockIds:function(){return"string"==typeof localStorage[Craft.MatrixInput.collapsedBlockStorageKey]?Craft.filterArray(localStorage[Craft.MatrixInput.collapsedBlockStorageKey].split(",")):[]},setCollapsedBlockIds:function(a){localStorage[Craft.MatrixInput.collapsedBlockStorageKey]=a.join(",")},rememberCollapsedBlockId:function(a){if("undefined"!==typeof Storage){var b=Craft.MatrixInput.getCollapsedBlockIds();
-1==c.inArray(""+a,b)&&(b.push(a),Craft.MatrixInput.setCollapsedBlockIds(b))}},forgetCollapsedBlockId:function(a){if("undefined"!==typeof Storage){var b=Craft.MatrixInput.getCollapsedBlockIds();a=c.inArray(""+a,b);-1!=a&&(b.splice(a,1),Craft.MatrixInput.setCollapsedBlockIds(b))}}});var n=Garnish.Base.extend({matrix:null,$container:null,$fieldsContainer:null,$previewContainer:null,$actionMenu:null,$collapsedInput:null,isNew:null,id:null,collapsed:!1,init:function(a,b){this.matrix=a;this.$container=
b;this.$fieldsContainer=b.children(".fields");this.id=this.$container.data("id");this.isNew=!this.id||"string"==typeof this.id&&"new"==this.id.substr(0,3);var d=this.$container.find("> .actions > .settings"),d=new Garnish.MenuBtn(d);this.$actionMenu=d.menu.$container;d.menu.settings.onOptionSelect=c.proxy(this,"onMenuOptionSelect");this.$container.data("collapsed")&&this.collapse();this.addListener(this.$container,"dblclick",function(a){a.pageY<=this.$container.offset().top+30&&(a.preventDefault(),
this.toggle())})},toggle:function(){this.collapsed?this.expand():this.collapse(!0)},collapse:function(a){if(!this.collapsed){this.$previewContainer||(this.$previewContainer=c('<div class="preview" style="display: none;"/>').appendTo(this.$container));for(var b="",d=this.$fieldsContainer.children(),g=0;g<d.length;g++){for(var h=c(d[g]),l=h.children(".input").find('select,input[type!="hidden"],textarea,.label'),f="",k=0;k<l.length;k++){var e=c(l[k]);if(e.hasClass("label")){var m=e.parent().parent();
if(m.hasClass("lightswitch")&&(m.hasClass("on")&&e.hasClass("off")||!m.hasClass("on")&&e.hasClass("on")))continue;e=e.text()}else e=Craft.getText(Garnish.getInputPostVal(e));e instanceof Array&&(e=e.join(", "));e&&(e=Craft.trim(e))&&(f&&(f+=", "),f+=e)}f&&(b&&(b+=" <span>|</span> "),b+="<strong>"+Craft.trim(h.children(".heading").text())+":</strong> "+f)}this.$previewContainer.html(b);this.$previewContainer.stop();this.$fieldsContainer.stop();this.$container.stop();a?(this.$previewContainer.fadeIn("fast"),
this.$fieldsContainer.fadeOut("fast"),this.$container.animate({height:0},"fast")):(this.$previewContainer.show(),this.$fieldsContainer.hide(),this.$container.css({height:0}));setTimeout(c.proxy(function(){this.$actionMenu.find("a[data-action=collapse]:first").parent().addClass("hidden");this.$actionMenu.find("a[data-action=expand]:first").parent().removeClass("hidden")},this),200);this.isNew?this.$collapsedInput?this.$collapsedInput.val("1"):this.$collapsedInput=c('<input type="hidden" name="'+this.matrix.inputNamePrefix+
"["+this.id+'][collapsed]" value="1"/>').appendTo(this.$container):Craft.MatrixInput.rememberCollapsedBlockId(this.id);this.collapsed=!0}},expand:function(){if(this.collapsed){this.$previewContainer.stop();this.$fieldsContainer.stop();this.$container.stop();var a=this.$container.height();this.$container.height("auto");this.$fieldsContainer.show();var b=this.$container.height();this.$container.height(a);this.$fieldsContainer.hide().fadeIn("fast");this.$previewContainer.fadeOut("fast");this.$container.animate({height:b},
"fast",c.proxy(function(){this.$container.height("auto")},this));setTimeout(c.proxy(function(){this.$actionMenu.find("a[data-action=collapse]:first").parent().removeClass("hidden");this.$actionMenu.find("a[data-action=expand]:first").parent().addClass("hidden")},this),200);this.isNew||"undefined"===typeof Storage||(a=Craft.MatrixInput.getCollapsedBlockIds(),b=c.inArray(""+this.id,a),-1!=b&&(a.splice(b,1),Craft.MatrixInput.setCollapsedBlockIds(a)));this.isNew?this.$collapsedInput&&this.$collapsedInput.val(""):
Craft.MatrixInput.forgetCollapsedBlockId(this.id);this.collapsed=!1}},disable:function(){this.$container.children('input[name$="[enabled]"]:first').val("");this.$container.addClass("disabled");setTimeout(c.proxy(function(){this.$actionMenu.find("a[data-action=disable]:first").parent().addClass("hidden");this.$actionMenu.find("a[data-action=enable]:first").parent().removeClass("hidden")},this),200);this.collapse(!0)},enable:function(){this.$container.children('input[name$="[enabled]"]:first').val("1");
this.$container.removeClass("disabled");setTimeout(c.proxy(function(){this.$actionMenu.find("a[data-action=disable]:first").parent().removeClass("hidden");this.$actionMenu.find("a[data-action=enable]:first").parent().addClass("hidden")},this),200);this.expand()},onMenuOptionSelect:function(a){a=c(a);switch(a.data("action")){case "collapse":this.collapse(!0);break;case "expand":this.expand();break;case "disable":this.disable();break;case "enable":this.enable();break;case "add":a=a.data("type");this.matrix.addBlock(a,
this.$container);break;case "delete":this.selfDestruct()}},selfDestruct:function(){this.$container.animate(this.matrix.getHiddenBlockCss(this.$container),"fast",c.proxy(function(){this.$container.remove();this.matrix.updateAddBlockBtn()},this))}})})(jQuery);

//# sourceMappingURL=MatrixInput.min.map
