/*
 Copyright (c) 2014, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @link      http://buildwithcraft.com
*/
(function(f){Craft.RichTextInput=Garnish.Base.extend({id:null,sectionSources:null,elementLocale:null,redactorConfig:null,$textarea:null,redactor:null,init:function(a,b,e,c,d){this.id=a;this.sectionSources=b;this.elementLocale=e;this.redactorConfig=c;this.redactorConfig.lang=d;this.redactorConfig.direction=Craft.orientation;this.$textarea=f("#"+this.id);this.initRedactor();"undefined"!=typeof Craft.livePreview&&(Craft.livePreview.on("beforeEnter beforeExit",f.proxy(function(){this.redactor.destroy()},
this)),Craft.livePreview.on("enter slideOut",f.proxy(function(){this.initRedactor()},this)))},initRedactor:function(){this.$textarea.redactor(this.redactorConfig);this.redactor=this.$textarea.data("redactor");this.replaceRedactorButton("image",Craft.t("Insert image"),null,{from_web:{title:Craft.t("Insert URL"),func:"imageShow"},from_assets:{title:Craft.t("Choose image"),callback:function(){this.selectionSave();var a=this;"undefined"==typeof this.assetSelectionModal?this.assetSelectionModal=Craft.createElementSelectorModal("Asset",
{storageKey:"RichTextFieldType.ChooseImage",multiSelect:!0,criteria:{locale:this.elementLocale,kind:"image"},onSelect:f.proxy(function(b,e){if(b.length){a.selectionRestore();for(var c=0;c<b.length;c++){var d=b[c],d=d.url+"#asset:"+d.id;e&&(d+=":"+e);a.insertNode(f('<img src="'+d+'" />')[0]);a.sync()}this.observeImages();a.dropdownHideAll()}},this),closeOtherModals:!1,canSelectImageTransforms:!0}):this.assetSelectionModal.show()}}});this.replaceRedactorButton("link",Craft.t("Link"),null,{link_entry:{title:Craft.t("Link to an entry"),
callback:function(){this.selectionSave();var a=this;"undefined"==typeof this.entrySelectionModal?this.entrySelectionModal=Craft.createElementSelectorModal("Entry",{storageKey:"RichTextFieldType.LinkToEntry",sources:this.sectionSources,criteria:{locale:this.elementLocale},onSelect:function(b){if(b.length){a.selectionRestore();b=b[0];var e=b.url+"#entry:"+b.id,c=a.getSelectionText();a.insertNode(f('<a href="'+e+'">'+(0<c.length?c:b.label)+"</a>")[0]);a.sync()}a.dropdownHideAll()},closeOtherModals:!1}):
this.entrySelectionModal.show()}},link_asset:{title:Craft.t("Link to an asset"),callback:function(){this.selectionSave();var a=this;"undefined"==typeof this.assetLinkSelectionModal?this.assetLinkSelectionModal=Craft.createElementSelectorModal("Asset",{storageKey:"RichTextFieldType.LinkToAsset",criteria:{locale:this.elementLocale},onSelect:function(b){if(b.length){a.selectionRestore();b=b[0];var e=b.url+"#asset:"+b.id,c=a.getSelectionText();a.insertNode(f('<a href="'+e+'">'+(0<c.length?c:b.label)+
"</a>")[0]);a.sync()}a.dropdownHideAll()},closeOtherModals:!1,canSelectImageTransforms:!0}):this.assetLinkSelectionModal.show()}},link:{title:Craft.t("Insert link"),func:"linkShow"},unlink:{title:Craft.t("Unlink"),exec:"unlink"}});if("undefined"!=typeof this.redactor.fullscreen&&"function"==typeof this.redactor.toggleFullscreen)Craft.cp.on("beforeSaveShortcut",f.proxy(function(){this.redactor.fullscreen&&this.redactor.toggleFullscreen()},this))},replaceRedactorButton:function(a,b,e,c){if(this.redactor.buttonGet(a).length){var d=
a+"_placeholder";this.redactor.buttonAddAfter(a,d);this.redactor.buttonRemove(a);this.redactor.buttonAddAfter(d,a,b,e,c);this.redactor.buttonRemove(d)}}})})(jQuery);

//# sourceMappingURL=RichTextInput.min.map
