/*
 Copyright (c) 2014, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @link      http://buildwithcraft.com
*/
(function(b){Craft.UpdateInfo=Garnish.Base.extend({appUpdateInfo:null,$container:null,$downloadBtn:null,licenseHud:null,$licenseSubmitBtn:null,licenseSubmitAction:null,allowAutoUpdates:null,init:function(a){this.allowAutoUpdates=a;var c=b("#graphic"),d=b("#status");Craft.postActionRequest("update/getAvailableUpdates",b.proxy(function(a,f){if("success"!=f||a.error||a.errors){var e=Craft.t("An unknown error occurred.");a.errors&&a.errors.length?e=a.errors[0]:a.error&&(e=a.error);c.addClass("error");
d.text(e)}else e={total:a.app&&a.app.releases&&a.app.releases.length?1:0,critical:a.app&&a.criticalUpdateAvailable},e.total?(c.fadeOut("fast"),d.fadeOut("fast",b.proxy(function(){c.remove();d.remove();this.appUpdateInfo=a.app;this.showAvailableUpdates()},this))):(c.addClass("success"),d.text(Craft.t("You\u2019re all up-to-date!"))),Craft.cp.displayUpdateInfo(e)},this))},showAvailableUpdates:function(){this.$container=b("<div/>").appendTo(Craft.cp.$main).hide();var a=b('<div class="pane clearafter"/>').appendTo(this.$container);
b('<h2 class="heading">'+Craft.t("You\u2019ve got updates!")+"</h2>").appendTo(a);a=b('<div class="buttons"/>').appendTo(a);if(this.appUpdateInfo.manualUpdateRequired)this.$downloadBtn=b('<div class="btn submit">'+Craft.t("Download")+"</div>").appendTo(a);else if(this.allowAutoUpdates){var c=b('<div class="btngroup submit"/>').appendTo(a),d=b('<div class="btn submit">'+Craft.t("Update")+"</div>").appendTo(c),a=b('<div class="btn submit menubtn"/>').appendTo(c),c=b('<div class="menu" data-align="right"/>').appendTo(c),
c=b("<ul/>").appendTo(c),c=b("<li/>").appendTo(c);this.$downloadBtn=b("<a>"+Craft.t("Download")+"</a>").appendTo(c);new Garnish.MenuBtn(a)}this.allowAutoUpdates&&(this.appUpdateInfo.licenseUpdated?(this.addListener(this.$downloadBtn,"click","showLicenseForm"),this.appUpdateInfo.manualUpdateRequired||this.addListener(d,"click","showLicenseForm")):(this.addListener(this.$downloadBtn,"click","downloadThat"),this.appUpdateInfo.manualUpdateRequired||this.addListener(d,"click","autoUpdateThat")));this.showReleases(this.appUpdateInfo.releases,
"Craft");this.$container.fadeIn("fast")},showLicenseForm:function(a){a.stopPropagation();if(this.licenseHud)this.licenseHud.$trigger=b(a.currentTarget),this.licenseHud.show();else{var c=b("<form><p>"+Craft.t('Craft\u2019s <a href="http://buildwithcraft.com/license" target="_blank">Terms and Conditions</a> have changed.')+"</p></form>"),d=b("<label> "+Craft.t("I agree.")+" &nbsp;</label>").appendTo(c),g=b('<input type="checkbox"/>').prependTo(d);this.$licenseSubmitBtn=b('<input class="btn submit" type="submit"/>').appendTo(c);
this.licenseHud=new Garnish.HUD(a.currentTarget,c);this.addListener(c,"submit",function(a){a.preventDefault();g.prop("checked")?(this.licenseSubmitAction(),this.licenseHud.hide(),g.prop("checked",!1)):Garnish.shake(this.licenseHud.$hud)})}a.currentTarget==this.$downloadBtn[0]?(this.$licenseSubmitBtn.attr("value",Craft.t("Seriously, download.")),this.licenseSubmitAction=this.downloadThat):(this.$licenseSubmitBtn.attr("value",Craft.t("Seriously, update.")),this.licenseSubmitAction=this.autoUpdateThat)},
showReleases:function(a,c){for(var d=0;d<a.length;d++){var g=b('<div class="pane"/>').appendTo(this.$container),f=a[d],e=c+" "+f.version;f.build&&(e+=' <span class="light">'+Craft.t("build {build}",{build:f.build})+"</span>");f.critical&&(e+=' <span class="critical">'+Craft.t("Critical")+"</span>");b("<h2>"+e+"</h2>").appendTo(g);b('<div class="notes"/>').appendTo(g).html(f.notes)}},downloadThat:function(){var a=this.appUpdateInfo.manualDownloadEndpoint;"https:"==window.location.protocol&&(a=a.replace("http:",
"https:"));b("<iframe/>",{src:a}).appendTo(Garnish.$bod).hide()},autoUpdateThat:function(){window.location.href=Craft.getUrl("updates/go/craft")}})})(jQuery);

//# sourceMappingURL=updates.min.map
